
%% Test qq
displayResultsV8( '/home/mkfinne2/Mindfulness/First_Level_Analysis',...
    {'NoMask', 'Using_Amgydala_ROI', 'Using_Average_Mask', 'Using_Individual_Masks'},...
    { 'Im', [], 'k', 0, 'Ic', 1 }, { 'thresDesc', 'FWE', 'u', 0.05 } );
 
%% Cycle through all first-level analyses.
displayResultsV8( '/home/mkfinne2/Mindfulness/First_Level_Analysis',...
    {'Using_Parahippocampus_ROI'},...
    { 'Im', [], 'k', 0 }, { 'Ic', [1:6] }, { 'thresDesc', { 'FWE', 'none' }, 'u', { 0.05, 0.001 } } );

%% Cycle through all within-session second-level analyses.
displayResultsV8( '/home/mkfinne2/Mindfulness/Second_Level_Analysis',...
    {'Using_Amgydala_ROI/within_session_activations'},...
    { 'Im', [], 'k', 0 , 'Ic', 1, 'thresDesc', 'none', 'u', 0.2 } );

%% Cycle through all between-session second-level analyses.
displayResultsV8( '/home/mkfinne2/Mindfulness/Second_Level_Analysis',...
    {'Using_Amgydala_ROI/between_session_t-tests'},...
    { 'Im', [], 'k', 0, 'thresDesc', 'none', 'u', 0.2 }, { 'Ic', [1:2] } );